### ISSUE TITLE
Option for dropping prefixes from channel names

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#100]
In current ISIS systems the channel prefixes are truncated before data reaches Mantid. It would be useful to have the option for the Forwarder to do this rather than populating the "source" field of the Kafka message with the entire channel name.

**Comment by zjttoefs** [comment]
Not sure I like the idea of introducing some string mangling there. But in the configuration we could optionally send a source name to use instead of the raw PV.

**Comment by matthew-d-jones** [comment]
I think this would be a reasonable feature for the following reasons:
- In Kafka we are aggregating PVs by instrument anyway, the topic name contains the instrument name so no information is lost.
- If the instrument name is not dropped from the channel name it seems likely you'll have instrument scientists asking why they have to type their instrument name every time they want to filter on some sample environment parameter.
- I prefer a non-default option on the forwarder to specifying it in the configuration messages because it seems less prone to inconsistencies and has lower code complexity. Those advantages are due to it being less flexible though, if there is a use case for renaming rather than just truncating then we should go that route.

**Comment by matthew-d-jones** [comment]
Ignore the previous comment, it is apparently all prefixes which are removed at ISIS, not just an instrument name. This works fine at ISIS due to the forwarder only forwarding IBEX "blocks", which guarantees that the truncated name is unique. This feature doesn't make sense for the ESS.

**Comment by zjttoefs** [comment]
Strictly speaking the name only needs to be unique within a given topic. 
But what's your route to make this work for ISIS now?

**Comment by matthew-d-jones** [comment]
I need to figure out how to make this work for ISIS.

**Comment by matthew-d-jones** [comment]
Replaced by JIRA ticket DM-1258.
