### ISSUE TITLE
Build unit tests by default

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/forward-epics-to-kafka#101]
Currently cmake takes the -DREQUIRE_GTEST=TRUE to build the tests.
Now that we use Conan it probably makes more sense to have the tests build by default.

Perhaps a -DSKIP_TESTS option would be better.

**Comment by rerpha** [comment]
The default for `REQUIRE_GTEST` is false, i can set it to true. that way if explicitly told `REQUIRE_GTEST`=false it won't build the tests by default.
