### ISSUE TITLE
Have the forwarder dump its configuration into Kafka

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/forward-epics-to-kafka#110]
It would be useful if the forwarder dumped its configuration to a Kafka topic when it changes (or periodically if it changes frequently).

Initially this would be useful for debugging, but in the longer term it might be a way for the forwarder to recover its settings on a restart (#111).

**Comment by matthew-d-jones** [comment]
The config dump message should also contain the offset in the configuration topic which the Forwarder has reached. When recovering, the Forwarder can then consume any new config messages after that offset.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1138
