### ISSUE TITLE
Recover configuration from a Kafka topic

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#111]
Blocked by #110 

Use configuration dump messages to recover previous configuration on startup. For example to recover from a crash. The configuration dump message should also contain the offset in the configuration topic which the previous Forwarder instance reached, the topic should be rejoined at that point so that config changes published whilst the Forwarder was down are not ignored.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1139
