### ISSUE TITLE
Is a scalar value message really 112 bytes?

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#115]
If the statistics reported by the Forwarder are correct then a scalar value pv update message is 112 bytes. This seems very large.

**Comment by rerpha** [comment]
A lot of the payload is the extra options for debugging in the forwarder, which is set to true on the master build currently. 

these are `seq_data`, `seq_fwd` etc 

@dominikwerder are these used in tests anymore? I think they were being used in the `remote.cpp` tests that no longer exist. 

Either can we set these options to not be included in the flatbuffers by default (there is already a condition in place for this in the `f142.cpp` schema) or remove them entirely from both the schemas and the schema decompilers?
