### ISSUE TITLE
Forwarder requires LD_LIBRARY_PATH as env var to run 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/forward-epics-to-kafka#161]
When the executable is run without LD_LIBRARY_PATH as an environment variable when being built this is shown in the console: 

`build/forwarder/forward-epics-to-kafka: error while loading shared libraries: libCom.so.3.16.1: cannot open shared object file: No such file or directory`

I think this is something to do with EPICS. as a workaround for now set the environment variable to your build directory/`lib`

Fixing this would allow us to have no dependence on EPICS on the Jenkins node (we could then remove the `eee` label requirement in the Jenkinsfile).

**Comment by dominikwerder** [comment]
The `libCom` is indeed from EPICS.

Not sure if that helps, but I can say that I never used `LD_LIBRARY_PATH` for the forwarder, neither at build nor run time, Linux or OSX.

Maybe some issue with the conan package?

**Comment by rerpha** [comment]
@dominikwerder I also think it's something to do with the conan package, as before when i was using epics without the conan library i didn't require it. 

Have only just started using LD_LIBRARY_PATH and it seems to work for now

**Comment by amues** [comment]
I built the forwarder on _essdmscdm/ubuntu18.04-build-node:1.2.0_ and ran `readelf` on the binary:
```
readelf --dynamic forward-epics-to-kafka 

Dynamic section at offset 0x291528 contains 36 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpvData.so.6.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpvAccess.so.5.0.0]
 0x0000000000000001 (NEEDED)             Shared library: [libnt.so.5.1]
 0x0000000000000001 (NEEDED)             Shared library: [librdkafka.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/conan/.conan/data/epics/3.16.1-4.6.0-dm6/ess-dmsc/stable/package/b59f9d8e4901ad04cca04cbf6f6f2dcb63849aa2/lib:/conan/.conan/data/fmt/3.0.2-dm1/ess-dmsc/stable/package/b60023f9fa06321277cb53d223d0048027c27904/lib:/conan/.conan/data/graylog-logger/1.0.5-dm1/ess-dmsc/stable/package/b60023f9fa06321277cb53d223d0048027c27904/lib:/conan/.conan/data/gtest/3121b20-dm2/ess-dmsc/stable/package/546f8098572f5b4c6854d2aa82becc18a8dd60dd/lib:/conan/.conan/data/librdkafka/0.11.4/ess-dmsc/stable/package/08fec0811f248aa34ee7f475ad4f847af539ddb7/lib:/conan/.conan/data/FlatBuffers/1.9.0/ess-dmsc/stable/package/546f8098572f5b4c6854d2aa82becc18a8dd60dd/lib:/conan/.conan/data/zlib/1.2.11/conan/stable/package/cc7c6ef50e2fc4146124f5d9a34e6165110c37d1/lib]
...
```
I believe this issue is related to the deprecation of _RPATH_ and adoption of _RUNPATH_ that happens with more recent compilers (I did not observe this issue in a CentOS 7 build). The immediate dependencies are found correctly, but transitive dependencies are not.

For running the application without sourcing _activate_run.sh_, I believe the Conan libraries will need to be updated. I have a JIRA ticket for this (DM-837).

**Comment by mattclarke** [comment]
@amues has another issue for this https://jira.esss.lu.se/browse/DM-837, so I am closing this one.
