### ISSUE TITLE
Investigate why system-tests take so long to build/run

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#172]
Build time should be the same as for unit test jobs, docker images should be in local cache on the Jenkins node, the pytest tests themselves don't take very long to run... so why can it take 20 mins to run the job?

**Comment by rerpha** [comment]
When the issue is found the same sort of fix should be applied to the filewriter image as this is taking just as long.

**Comment by rerpha** [comment]
This is due to the conan stuff being executed during the build, the fix is to add a flag for the cmake to skip conan installation steps and run it earlier in the dockerfile. this way it won't have to be run every time even if the source changes. 

this needs to be done on the filewriter also.
