### ISSUE TITLE
Try replacing complex route and batch logic with shared_mutex protected map

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#176]
The logic related to routing PVs to a particular Kafka broker and topic is quite complex and unintuitive. Try replacing with something like `map<pvname, vector<pair<broker, topic>>>`. Pass single PV updates through the queues rather than batching. Conversion workers require only read access (shared lock on mutex) to the map to know where to send the resultant flatbuffer. Only the config listener requires write access to map (unique lock on mutex) so slow down from shared state between threads is unlikely to cause any performance problem, especially as the EPICS interface is the current bottleneck.

The hope is that this would provide a significant reduction in lines of code and a more simple and comprehensible architecture overall.

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1136
