### ISSUE TITLE
Create replacement for KafkaW using the rdkafka C++ API

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#177]
Ensure can be faked/mocked at a level where it is a thin wrapper over rdkafka C++ API.
Probably makes sense to make as a separate library, conanise and replace `KafkaW`in the File Writer with the same thing, check this!

**Comment by mattclarke** [comment]
Moved to https://jira.esss.lu.se/browse/DM-1137
