### ISSUE TITLE
Monitoring via Channel Access does not see the time stamp

### ISSUE THREAD

**Issue by dominikwerder** [ess-dmsc/forward-epics-to-kafka#22]
The forwarder does not see the time stamp on updates coming from e.g. the motors in the sinq amorsim. Thank @nikhilbiyani for reporting.

**Comment by SkyToGround** [comment]
This appears to be a problem with the pvAccess library. It appears to have been partially but not completely fixed in the master branch of pvAccess. pvAccessCPP issue #71 deals with this.
