### ISSUE TITLE
The forwarder is excessively verbose on stdout by default

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/forward-epics-to-kafka#30]
The forwarder prints an excessive amount of text to stdout by default which can make it hard to debug problems. The forwarder should only be verbose when explicitly requested (i.e. through command line argument) or by writing to its own private log file.

**Comment by dominikwerder** [comment]
Yes, it shouldn't be so verbose by default, thanks for reporting!

**Comment by rerpha** [comment]
No longer an issue, on a successful run the forwarder only prints this to stdout: 
` Activating forwarder run environment`
`Launching forwarder`
