### ISSUE TITLE
Create a Windows build Jenkins job

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#39]
Create Windows build in the pipeline script.

Current, manually configured, build is here: https://jenkins.esss.dk/dm/job/forward-epics-to-kafka-windows/

**Comment by matthew-d-jones** [comment]
There is already a build, but it doesn't report on PRs: https://jenkins.esss.dk/dm/job/forward-epics-to-kafka-windows/

**Comment by matthew-d-jones** [comment]
https://github.com/ess-dmsc/conan-epics-win32-fix

**Comment by mattclarke** [comment]
Is this issue obsolete now the windows build is working?

https://github.com/ess-dmsc/forward-epics-to-kafka/pull/48
