### ISSUE TITLE
Replace ring buffer implementation

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forward-epics-to-kafka#96]
We can remove a chunk of code from code that we have to maintain, and there _may_ be performance to gain from switching to a lock-free implementation.
The following implementation seems to be more highly regarded than the options available in boost:
https://github.com/cameron314/concurrentqueue

Benchmarking:
https://github.com/Qihoo360/evpp/blob/master/docs/benchmark_lockfree_vs_mutex.md#brief

**Comment by rerpha** [comment]
Todo: create conan package for concurrentqueue
